export const API = {
	GET_DATA: 'GET_DATA',
	SET_DATA: 'SET_DATA',
	SET_ERROR: 'SET_ERROR',
};

export const auth = {
	LOGIN: 'LOGIN',
	LOGOUT: 'LOGOUT',
};

export const expenses = {
	ADD: 'ADD_EXPENSE',
	REMOVE: 'REMOVE_EXPENSE',
	UPDATE: 'UPDATE_EXPENSE',
};

export const filters = {
	SET_END_DATE: 'SET_END_DATE',
	SET_TEXT_FILTER: 'SET_TEXT_FILTER',
	SET_START_DATE: 'SET_START_DATE',
	SORT_BY_AMOUNT: 'SORT_BY_AMOUNT',
	SORT_BY_DATE: 'SORT_BY_DATE',
};
